import streamlit as st
import datetime
import requests
import sys

BASE_URL = "http://localhost:8000" # Backend URL

st.set_page_config(
    page_title="AI Trip Planner",
    page_icon=":airplane:",
    layout="centered",
    initial_sidebar_state="expanded",
)

st.title()

# Initialize chat history in session state
if "messages" not in st.session_state:
    st.session_state.messages = []

st.header()

with st.form():
    user_input=st.text_input("User Input", placeholder="Enter your travel query here...")
    submit_button = st.form_submit_button("Submit")

if submit_button and user_input.strip():
    try:
        # Show User Message
        # Show thinking spinner while backend processes
        with st.spinner("Bot is thinking..."):
            payload = {"query": user_input}
            response = requests.post(f"{BASE_URL}/query", json=payload)

            if response.status_code == 200:
                answer = response.json()
                bot_response = answer.get("answer", "Sorry, I couldn't process your request.")
                markdown_content = f"""# 🌏AI Travel Plan

                # **Generated:** {datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
                ## **User Query:**
                {user_input}

                ---
                {answer}
                ---

                * This travel plan was generated by AI. Please review the details and make any necessary adjustments based on your preferences and requirements. Safe travels! *

                """
                st.markdown(markdown_content)
            else:
                st.error(f"Error from backend: {response.status_code} - {response.text}")
    except Exception as e:
        st.error(f"An error occurred: {str(e)}")